services:
  - type: web
    name: gest-test
    plan: starter
    env: python
    region: frankfurt  # region should be same as your database region.
    buildCommand: ".deployment/build.sh"
    startCommand: "gunicorn -b :5005 run:app"
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4